services:
#    cngot.example:
#        class: CNGOTBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

   redirect.after.login:
     class: CNGOTBundle\Redirection\AfterLoginRedirection
     arguments: [@router]

   app.mail.controller:
     class: CNGOTBundle\Controller\MailController
